### ISSUE TITLE
Does not compile in error es2016 preset?

### ISSUE THREAD

**Issue by nakawankuma** [toniov/p-iteration#12]
[16:35:09] Error: Couldn't find preset "es2016" relative to directory "C:\\src\\w-azure\\WebSite\\w\\node_modules\\p-iteration" while parsing file: C:\src\w-azure\WebSite\w\node_modules\p-iteration\index.js

I buling project uses 
React, Browserify, Babel(es2015), Gulp and others...
I've import P-iteration so have compile error .
I can send project information. 
If you have the necessary information, please say me.

**Comment by toniov** [comment]
Hi!

Have you installed `babel-preset-es2016` npm module? Also, I think you need `babel-preset-es2016` as well.

**Comment by nakawankuma** [comment]
I installed es2015. I tell es2016 install.
>package.json
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2016": "^6.24.1",
but I see compile error .
>Couldn't find preset "es2017" relative to directory

I more install es2017.
>package.json
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
>Gulp.js

    return browserify(
            {
            entries:  'jsxsrc/app.jsx', debug: true,
            })
        .transform(babelify, { presets: ["react", 'es2017'] })

I take green, but take a runtime exception.
"regeneratorRuntime is not defined"

I copy static find method and revert setting....

**Comment by nakawankuma** [comment]
ok.
thank you toniov.
I think install babel-polyfill.
thank you.

**Comment by toniov** [comment]
You're welcome :)

Feel free to open another issue if you have any problem.

**Comment by nakawankuma** [comment]
I installed polifill and more.
pcakage.json
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react": "^6.24.1",
but I tell message "regeneratorRuntime is not defined".
I Change "static-methods.js" 
import 'babel-polyfill'; 
will done.

Do you think about it?
I use polyfill in first time. I dont know change is correct.

**Comment by toniov** [comment]
According to the the Q/A I linked before, it seems you also need `babel-core` to make it work.

**Comment by nakawankuma** [comment]
Oh I mistake.
before
app.js
import from xxxx
import 'babel-polyfill'; 

after
app.js
import 'babel-polyfill'; 
import from xxxx

Its done.

**Comment by nakawankuma** [comment]
> According to the the Q/A I linked before, it seems you also need `babel-core` to make it work.
