### ISSUE TITLE
"Failed to minify the code"

### ISSUE THREAD

**Issue by eric-khoury** [toniov/p-iteration#9]
Hi, I'm having an issue when using this library in a react project. The issue seems to that the lib is not ES5 compiled? When trying to `build` my project, I get the error:

`
Failed to minify the code from this file: 
./node_modules/p-iteration/lib/static-methods.js:11
`

Could it be something missing on my part?

**Comment by toniov** [comment]
Hi!

Could you tell what tool are you using to minify the module? Maybe the tool you are using is not compatible with recent ES versions.

**Comment by toniov** [comment]
Hi!

Could you tell me what tool are you using to minify the module? Maybe the tool you are using is not compatible with recent ES versions.

**Comment by toniov** [comment]
Closing this, if you have any problem open a new issue or reply here :)
